/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ryszard.jenvey' at '08/01/16 08:30' with Gradle 2.3
 *
 * @author ryszard.jenvey, @date 08/01/16 08:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
