import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ryszard.jenvey' at '08/01/16 08:30' with Gradle 2.3
 *
 * @author ryszard.jenvey, @date 08/01/16 08:30
 */
public class ThingyUnitTest {
    @Test public void testSomeLibraryMethod() {
        Thingy classUnderTest = new Thingy();
        assertTrue("myMethod should return 'true'", classUnderTest.myMethod());
    }
}
